# место для данных выделяется на машине чтобы избежать потери
kind: PersistentVolume
apiVersion: v1
metadata:
  name: rabbitmq-data-sigma
  namespace: rabbitmq
  labels:
    type: local
  annotations:
    volume.alpha.kubernetes.io/storage-class: rabbitmq-data-sigma
spec:
  storageClassName: rabbitmq-data-sigma
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: "/opt/rabbitmq-data-sigma"
