kind: Service
apiVersion: v1
metadata:
  namespace: rabbitmq
  name: rabbitmq
  labels:
    app: rabbitmq
    type: LoadBalancer
spec:
  type: NodePort
  ports:
    # порт для HTTP API клиентов
    - name: http
      protocol: TCP
      port: 15672
      targetPort: 15672
      nodePort: 31672
    # порт для AMQP 
    - name: amqp
      protocol: TCP
      port: 5672
      targetPort: 5672
      nodePort: 30672
  selector:
    app: rabbitmq
